/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AzureFoundryDeploymentMasterData = {
  hasFunctions: boolean;
  id: string;
  inputCost: number;
  metadata?: { [k: string]: any } | undefined;
  modelDeveloper: string | null;
  modelFamily: string | null;
  modelId: string;
  modelType: string;
  outputCost: number;
  parameters: Array<any> | null;
};

/** @internal */
export const AzureFoundryDeploymentMasterData$inboundSchema: z.ZodType<
  AzureFoundryDeploymentMasterData,
  z.ZodTypeDef,
  unknown
> = z.object({
  has_functions: z.boolean(),
  id: z.string(),
  input_cost: z.number(),
  metadata: z.record(z.any()).optional(),
  model_developer: z.nullable(z.string()),
  model_family: z.nullable(z.string()),
  model_id: z.string(),
  model_type: z.string(),
  output_cost: z.number(),
  parameters: z.nullable(z.array(z.any())),
}).transform((v) => {
  return remap$(v, {
    "has_functions": "hasFunctions",
    "input_cost": "inputCost",
    "model_developer": "modelDeveloper",
    "model_family": "modelFamily",
    "model_id": "modelId",
    "model_type": "modelType",
    "output_cost": "outputCost",
  });
});

export function azureFoundryDeploymentMasterDataFromJSON(
  jsonString: string,
): SafeParseResult<AzureFoundryDeploymentMasterData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AzureFoundryDeploymentMasterData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AzureFoundryDeploymentMasterData' from JSON`,
  );
}
