/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Type discriminator indicating this is a conversation
 */
export const ConversationResponseKind = {
  Conversation: "conversation",
} as const;
/**
 * Type discriminator indicating this is a conversation
 */
export type ConversationResponseKind = ClosedEnum<
  typeof ConversationResponseKind
>;

/**
 * Optional metadata associated with the conversation.
 */
export type Metadata = {
  /**
   * Indicates whether the conversation title is currently being generated by AI.
   */
  generatingTitle?: boolean | undefined;
  /**
   * Identifier of the parent entity (agent, deployment, etc.) this conversation belongs to. Used for filtering conversations by entity.
   */
  entityId?: string | undefined;
};

export type ConversationResponse = {
  /**
   * Unique ULID (Universally Unique Lexicographically Sortable Identifier) for the conversation, prefixed with "conv_"
   */
  id?: string | undefined;
  /**
   * Identifier of the parent entity (agent, deployment, etc.) this conversation belongs to.
   */
  entityId: string;
  /**
   * Type discriminator indicating this is a conversation
   */
  kind: ConversationResponseKind;
  /**
   * Display name for the conversation. Can be auto-generated or set by the user.
   */
  displayName: string;
  /**
   * Unix timestamp (in milliseconds) when the conversation was created
   */
  createdAt: number;
  /**
   * Unix timestamp (in milliseconds) when the conversation was last updated
   */
  updatedAt: number;
  /**
   * Optional identifier of the user or agent that created the conversation
   */
  createdById?: string | undefined;
  /**
   * Optional identifier of the user or agent that last updated the conversation
   */
  updatedById?: string | undefined;
  /**
   * Optional metadata associated with the conversation.
   */
  metadata?: Metadata | undefined;
};

/** @internal */
export const ConversationResponseKind$inboundSchema: z.ZodNativeEnum<
  typeof ConversationResponseKind
> = z.nativeEnum(ConversationResponseKind);
/** @internal */
export const ConversationResponseKind$outboundSchema: z.ZodNativeEnum<
  typeof ConversationResponseKind
> = ConversationResponseKind$inboundSchema;

/** @internal */
export const Metadata$inboundSchema: z.ZodType<
  Metadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  generating_title: z.boolean().optional(),
  entity_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "generating_title": "generatingTitle",
    "entity_id": "entityId",
  });
});
/** @internal */
export type Metadata$Outbound = {
  generating_title?: boolean | undefined;
  entity_id?: string | undefined;
};

/** @internal */
export const Metadata$outboundSchema: z.ZodType<
  Metadata$Outbound,
  z.ZodTypeDef,
  Metadata
> = z.object({
  generatingTitle: z.boolean().optional(),
  entityId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    generatingTitle: "generating_title",
    entityId: "entity_id",
  });
});

export function metadataToJSON(metadata: Metadata): string {
  return JSON.stringify(Metadata$outboundSchema.parse(metadata));
}
export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const ConversationResponse$inboundSchema: z.ZodType<
  ConversationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string().default("conv_01kc3pkd45a38qw2m76ej9qjt8"),
  entity_id: z.string(),
  kind: ConversationResponseKind$inboundSchema,
  display_name: z.string(),
  created_at: z.number(),
  updated_at: z.number(),
  created_by_id: z.string().optional(),
  updated_by_id: z.string().optional(),
  metadata: z.lazy(() => Metadata$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "entity_id": "entityId",
    "display_name": "displayName",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "created_by_id": "createdById",
    "updated_by_id": "updatedById",
  });
});
/** @internal */
export type ConversationResponse$Outbound = {
  _id: string;
  entity_id: string;
  kind: string;
  display_name: string;
  created_at: number;
  updated_at: number;
  created_by_id?: string | undefined;
  updated_by_id?: string | undefined;
  metadata?: Metadata$Outbound | undefined;
};

/** @internal */
export const ConversationResponse$outboundSchema: z.ZodType<
  ConversationResponse$Outbound,
  z.ZodTypeDef,
  ConversationResponse
> = z.object({
  id: z.string().default("conv_01kc3pkd45a38qw2m76ej9qjt8"),
  entityId: z.string(),
  kind: ConversationResponseKind$outboundSchema,
  displayName: z.string(),
  createdAt: z.number(),
  updatedAt: z.number(),
  createdById: z.string().optional(),
  updatedById: z.string().optional(),
  metadata: z.lazy(() => Metadata$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
    entityId: "entity_id",
    displayName: "display_name",
    createdAt: "created_at",
    updatedAt: "updated_at",
    createdById: "created_by_id",
    updatedById: "updated_by_id",
  });
});

export function conversationResponseToJSON(
  conversationResponse: ConversationResponse,
): string {
  return JSON.stringify(
    ConversationResponse$outboundSchema.parse(conversationResponse),
  );
}
export function conversationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationResponse' from JSON`,
  );
}
