/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Resource type discriminator.
 */
export const ConversationResponseKind = {
  Conversation: "conversation",
} as const;
/**
 * Resource type discriminator.
 */
export type ConversationResponseKind = ClosedEnum<
  typeof ConversationResponseKind
>;

/**
 * Additional conversation metadata.
 */
export type Metadata = {
  /**
   * When `true`, indicates the conversation title is being auto-generated.
   */
  generatingTitle?: boolean | undefined;
  /**
   * Parent entity identifier (e.g., agent or deployment). Set to `null` for standalone conversations.
   */
  entityId?: string | null | undefined;
  /**
   * Model identifier for standalone conversations in `provider/model_id` format. Set to `null` for entity-bound conversations.
   */
  model?: string | null | undefined;
};

export type ConversationResponse = {
  /**
   * Unique conversation identifier with `conv_` prefix.
   */
  id?: string | undefined;
  /**
   * Resource type discriminator.
   */
  kind: ConversationResponseKind;
  /**
   * Human-readable name for the conversation. Maximum 100 characters.
   */
  displayName: string;
  /**
   * Unix timestamp in milliseconds when the conversation was created.
   */
  createdAt: number;
  /**
   * Unix timestamp in milliseconds when the conversation was last modified.
   */
  updatedAt: number;
  /**
   * Identifier of the user or system that created the conversation.
   */
  createdById?: string | undefined;
  /**
   * Identifier of the user or system that last modified the conversation.
   */
  updatedById?: string | undefined;
  /**
   * Additional conversation metadata.
   */
  metadata?: Metadata | undefined;
};

/** @internal */
export const ConversationResponseKind$inboundSchema: z.ZodNativeEnum<
  typeof ConversationResponseKind
> = z.nativeEnum(ConversationResponseKind);
/** @internal */
export const ConversationResponseKind$outboundSchema: z.ZodNativeEnum<
  typeof ConversationResponseKind
> = ConversationResponseKind$inboundSchema;

/** @internal */
export const Metadata$inboundSchema: z.ZodType<
  Metadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  generatingTitle: z.boolean().optional(),
  entityId: z.nullable(z.string()).optional(),
  model: z.nullable(z.string()).optional(),
});
/** @internal */
export type Metadata$Outbound = {
  generatingTitle?: boolean | undefined;
  entityId?: string | null | undefined;
  model?: string | null | undefined;
};

/** @internal */
export const Metadata$outboundSchema: z.ZodType<
  Metadata$Outbound,
  z.ZodTypeDef,
  Metadata
> = z.object({
  generatingTitle: z.boolean().optional(),
  entityId: z.nullable(z.string()).optional(),
  model: z.nullable(z.string()).optional(),
});

export function metadataToJSON(metadata: Metadata): string {
  return JSON.stringify(Metadata$outboundSchema.parse(metadata));
}
export function metadataFromJSON(
  jsonString: string,
): SafeParseResult<Metadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Metadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Metadata' from JSON`,
  );
}

/** @internal */
export const ConversationResponse$inboundSchema: z.ZodType<
  ConversationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string().default("conv_01kfbbz05cw2txnzg16bc914gk"),
  kind: ConversationResponseKind$inboundSchema,
  displayName: z.string(),
  createdAt: z.number(),
  updatedAt: z.number(),
  createdById: z.string().optional(),
  updatedById: z.string().optional(),
  metadata: z.lazy(() => Metadata$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
  });
});
/** @internal */
export type ConversationResponse$Outbound = {
  _id: string;
  kind: string;
  displayName: string;
  createdAt: number;
  updatedAt: number;
  createdById?: string | undefined;
  updatedById?: string | undefined;
  metadata?: Metadata$Outbound | undefined;
};

/** @internal */
export const ConversationResponse$outboundSchema: z.ZodType<
  ConversationResponse$Outbound,
  z.ZodTypeDef,
  ConversationResponse
> = z.object({
  id: z.string().default("conv_01kfbbz05cw2txnzg16bc914gk"),
  kind: ConversationResponseKind$outboundSchema,
  displayName: z.string(),
  createdAt: z.number(),
  updatedAt: z.number(),
  createdById: z.string().optional(),
  updatedById: z.string().optional(),
  metadata: z.lazy(() => Metadata$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    id: "_id",
  });
});

export function conversationResponseToJSON(
  conversationResponse: ConversationResponse,
): string {
  return JSON.stringify(
    ConversationResponse$outboundSchema.parse(conversationResponse),
  );
}
export function conversationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConversationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConversationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConversationResponse' from JSON`,
  );
}
