/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  McpAuthConfig,
  McpAuthConfig$Outbound,
  McpAuthConfig$outboundSchema,
} from "./mcpauthconfig.js";
import {
  McpConnection,
  McpConnection$Outbound,
  McpConnection$outboundSchema,
} from "./mcpconnection.js";
import {
  McpServerSharing,
  McpServerSharing$Outbound,
  McpServerSharing$outboundSchema,
} from "./mcpserversharing.js";
import {
  McpToolExposure,
  McpToolExposure$Outbound,
  McpToolExposure$outboundSchema,
} from "./mcptoolexposure.js";

export type CreateMcpServerRequest = {
  key?: string | undefined;
  displayName?: string | undefined;
  description?: string | undefined;
  projectId?: string | undefined;
  connection?: McpConnection | undefined;
  auth?: McpAuthConfig | undefined;
  defaultToolExposure?: McpToolExposure | undefined;
  sharing?: McpServerSharing | undefined;
};

/** @internal */
export type CreateMcpServerRequest$Outbound = {
  key?: string | undefined;
  display_name?: string | undefined;
  description?: string | undefined;
  project_id?: string | undefined;
  connection?: McpConnection$Outbound | undefined;
  auth?: McpAuthConfig$Outbound | undefined;
  default_tool_exposure?: McpToolExposure$Outbound | undefined;
  sharing?: McpServerSharing$Outbound | undefined;
};

/** @internal */
export const CreateMcpServerRequest$outboundSchema: z.ZodType<
  CreateMcpServerRequest$Outbound,
  z.ZodTypeDef,
  CreateMcpServerRequest
> = z.object({
  key: z.string().optional(),
  displayName: z.string().optional(),
  description: z.string().optional(),
  projectId: z.string().optional(),
  connection: McpConnection$outboundSchema.optional(),
  auth: McpAuthConfig$outboundSchema.optional(),
  defaultToolExposure: McpToolExposure$outboundSchema.optional(),
  sharing: McpServerSharing$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
    projectId: "project_id",
    defaultToolExposure: "default_tool_exposure",
  });
});

export function createMcpServerRequestToJSON(
  createMcpServerRequest: CreateMcpServerRequest,
): string {
  return JSON.stringify(
    CreateMcpServerRequest$outboundSchema.parse(createMcpServerRequest),
  );
}
