/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteEnvironmentResponse = {};

/** @internal */
export const DeleteEnvironmentResponse$inboundSchema: z.ZodType<
  DeleteEnvironmentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function deleteEnvironmentResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEnvironmentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEnvironmentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEnvironmentResponse' from JSON`,
  );
}
