/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteModelFusionResponse = {};

/** @internal */
export const DeleteModelFusionResponse$inboundSchema: z.ZodType<
  DeleteModelFusionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function deleteModelFusionResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteModelFusionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteModelFusionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteModelFusionResponse' from JSON`,
  );
}
