/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Log, Log$inboundSchema } from "./log.js";

export type GetLogResponse = {
  /**
   * Log is the canonical wire representation of an otel_logs row.
   */
  log?: Log | undefined;
};

/** @internal */
export const GetLogResponse$inboundSchema: z.ZodType<
  GetLogResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  log: Log$inboundSchema.optional(),
});

export function getLogResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetLogResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLogResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLogResponse' from JSON`,
  );
}
