/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SmartRouter, SmartRouter$inboundSchema } from "./smartrouter.js";

export type ListSmartRoutersResponse = {
  /**
   * Object type for this collection. Always `list`.
   */
  object: string;
  /**
   * Smart Routers in the current page.
   */
  data: Array<SmartRouter>;
  /**
   * Whether more Smart Routers are available in the requested pagination direction.
   */
  hasMore: boolean;
};

/** @internal */
export const ListSmartRoutersResponse$inboundSchema: z.ZodType<
  ListSmartRoutersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string(),
  data: z.array(SmartRouter$inboundSchema),
  has_more: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});

export function listSmartRoutersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSmartRoutersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSmartRoutersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSmartRoutersResponse' from JSON`,
  );
}
