/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Project, Project$inboundSchema } from "./project.js";

export type ListProjectsResponse = {
  object?: string | undefined;
  data?: Array<Project> | undefined;
  hasMore?: boolean | undefined;
};

/** @internal */
export const ListProjectsResponse$inboundSchema: z.ZodType<
  ListProjectsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  object: z.string().optional(),
  data: z.array(Project$inboundSchema).optional(),
  has_more: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    "has_more": "hasMore",
  });
});

export function listProjectsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListProjectsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListProjectsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListProjectsResponse' from JSON`,
  );
}
