/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  McpToolExposureMode,
  McpToolExposureMode$inboundSchema,
  McpToolExposureMode$outboundSchema,
} from "./mcptoolexposuremode.js";

export type McpToolExposure = {
  mode: McpToolExposureMode;
  /**
   * Keeps only the tools the upstream annotates as read-only.
   */
  readOnly?: boolean | undefined;
  /**
   * `McpTool.id` values to expose when mode is SELECTED; a tool renamed upstream gets a new id on the next sync.
   */
  toolIds?: Array<string> | undefined;
};

/** @internal */
export const McpToolExposure$inboundSchema: z.ZodType<
  McpToolExposure,
  z.ZodTypeDef,
  unknown
> = z.object({
  mode: McpToolExposureMode$inboundSchema,
  read_only: z.boolean().optional(),
  tool_ids: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "read_only": "readOnly",
    "tool_ids": "toolIds",
  });
});
/** @internal */
export type McpToolExposure$Outbound = {
  mode: string;
  read_only?: boolean | undefined;
  tool_ids?: Array<string> | undefined;
};

/** @internal */
export const McpToolExposure$outboundSchema: z.ZodType<
  McpToolExposure$Outbound,
  z.ZodTypeDef,
  McpToolExposure
> = z.object({
  mode: McpToolExposureMode$outboundSchema,
  readOnly: z.boolean().optional(),
  toolIds: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    readOnly: "read_only",
    toolIds: "tool_ids",
  });
});

export function mcpToolExposureToJSON(
  mcpToolExposure: McpToolExposure,
): string {
  return JSON.stringify(McpToolExposure$outboundSchema.parse(mcpToolExposure));
}
export function mcpToolExposureFromJSON(
  jsonString: string,
): SafeParseResult<McpToolExposure, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => McpToolExposure$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'McpToolExposure' from JSON`,
  );
}
