/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { McpTool, McpTool$inboundSchema } from "./mcptool.js";

export type McpTestResult = {
  /**
   * Whether the probe connected and listed tools successfully.
   */
  ok?: boolean | undefined;
  /**
   * Tools discovered during the probe; not persisted.
   */
  tools?: Array<McpTool> | undefined;
  /**
   * Round trip time of the probe in milliseconds.
   */
  latencyMs?: number | undefined;
  /**
   * Human-readable reason the probe failed.
   */
  errorMessage?: string | undefined;
  /**
   * Additional failure details collected during the probe.
   */
  errors?: Array<string> | undefined;
};

/** @internal */
export const McpTestResult$inboundSchema: z.ZodType<
  McpTestResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  ok: z.boolean().optional(),
  tools: z.array(McpTool$inboundSchema).optional(),
  latency_ms: z.number().int().optional(),
  error_message: z.string().optional(),
  errors: z.array(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "latency_ms": "latencyMs",
    "error_message": "errorMessage",
  });
});

export function mcpTestResultFromJSON(
  jsonString: string,
): SafeParseResult<McpTestResult, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => McpTestResult$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'McpTestResult' from JSON`,
  );
}
