/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Plugin discriminator. Must be `pii_redaction`.
 */
export const Id = {
  PiiRedaction: "pii_redaction",
} as const;
/**
 * Plugin discriminator. Must be `pii_redaction`.
 */
export type Id = ClosedEnum<typeof Id>;

/**
 * Behavior when redaction is unavailable. `block` (default) fails the request; `passthrough` sends the original text.
 */
export const OnFailure = {
  Block: "block",
  Passthrough: "passthrough",
} as const;
/**
 * Behavior when redaction is unavailable. `block` (default) fails the request; `passthrough` sends the original text.
 */
export type OnFailure = ClosedEnum<typeof OnFailure>;

export const Entities = {
  Age: "AGE",
  ApiKey: "API_KEY",
  BankRouting: "BANK_ROUTING",
  Bic: "BIC",
  BiometricId: "BIOMETRIC_ID",
  BloodType: "BLOOD_TYPE",
  Bsn: "BSN",
  CreditCard: "CREDIT_CARD",
  Crypto: "CRYPTO",
  DateTime: "DATE_TIME",
  DeviceId: "DEVICE_ID",
  EducationLevel: "EDUCATION_LEVEL",
  Email: "EMAIL",
  EmailAddress: "EMAIL_ADDRESS",
  EmploymentStatus: "EMPLOYMENT_STATUS",
  Gender: "GENDER",
  HealthPlanId: "HEALTH_PLAN_ID",
  HttpCookie: "HTTP_COOKIE",
  IbanCode: "IBAN_CODE",
  Id: "ID",
  IdCard: "ID_CARD",
  Imei: "IMEI",
  IpAddress: "IP_ADDRESS",
  Jobtitle: "JOBTITLE",
  Jwt: "JWT",
  KvkNumber: "KVK_NUMBER",
  Language: "LANGUAGE",
  LicenseNumber: "LICENSE_NUMBER",
  LicensePlate: "LICENSE_PLATE",
  Location: "LOCATION",
  MacAddress: "MAC_ADDRESS",
  MedicalLicense: "MEDICAL_LICENSE",
  MedicalRecord: "MEDICAL_RECORD",
  Nrp: "NRP",
  Organization: "ORGANIZATION",
  Passport: "PASSPORT",
  Password: "PASSWORD",
  Person: "PERSON",
  PhoneNumber: "PHONE_NUMBER",
  Pin: "PIN",
  PoliticalView: "POLITICAL_VIEW",
  RaceEthnicity: "RACE_ETHNICITY",
  ReligiousBelief: "RELIGIOUS_BELIEF",
  Sexuality: "SEXUALITY",
  TaxId: "TAX_ID",
  Title: "TITLE",
  UkNhs: "UK_NHS",
  Url: "URL",
  UsBankNumber: "US_BANK_NUMBER",
  UsDriverLicense: "US_DRIVER_LICENSE",
  UsItin: "US_ITIN",
  UsPassport: "US_PASSPORT",
  UsSsn: "US_SSN",
  Uuid: "UUID",
  VehicleId: "VEHICLE_ID",
} as const;
export type Entities = ClosedEnum<typeof Entities>;

export type PIIRedactionPluginEn = {
  /**
   * Plugin discriminator. Must be `pii_redaction`.
   */
  id: Id;
  /**
   * Behavior when redaction is unavailable. `block` (default) fails the request; `passthrough` sends the original text.
   */
  onFailure?: OnFailure | undefined;
  /**
   * Detector confidence cutoff in [0,1].
   */
  threshold?: number | undefined;
  /**
   * Detector language.
   */
  language: "en";
  /**
   * English entity types to redact. Omit to redact every type detected for the language.
   */
  entities?: Array<Entities> | undefined;
};

/** @internal */
export const Id$inboundSchema: z.ZodNativeEnum<typeof Id> = z.nativeEnum(Id);
/** @internal */
export const Id$outboundSchema: z.ZodNativeEnum<typeof Id> = Id$inboundSchema;

/** @internal */
export const OnFailure$inboundSchema: z.ZodNativeEnum<typeof OnFailure> = z
  .nativeEnum(OnFailure);
/** @internal */
export const OnFailure$outboundSchema: z.ZodNativeEnum<typeof OnFailure> =
  OnFailure$inboundSchema;

/** @internal */
export const Entities$inboundSchema: z.ZodNativeEnum<typeof Entities> = z
  .nativeEnum(Entities);
/** @internal */
export const Entities$outboundSchema: z.ZodNativeEnum<typeof Entities> =
  Entities$inboundSchema;

/** @internal */
export const PIIRedactionPluginEn$inboundSchema: z.ZodType<
  PIIRedactionPluginEn,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: Id$inboundSchema,
  on_failure: OnFailure$inboundSchema.optional(),
  threshold: z.number().optional(),
  language: z.literal("en"),
  entities: z.array(Entities$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "on_failure": "onFailure",
  });
});
/** @internal */
export type PIIRedactionPluginEn$Outbound = {
  id: string;
  on_failure?: string | undefined;
  threshold?: number | undefined;
  language: "en";
  entities?: Array<string> | undefined;
};

/** @internal */
export const PIIRedactionPluginEn$outboundSchema: z.ZodType<
  PIIRedactionPluginEn$Outbound,
  z.ZodTypeDef,
  PIIRedactionPluginEn
> = z.object({
  id: Id$outboundSchema,
  onFailure: OnFailure$outboundSchema.optional(),
  threshold: z.number().optional(),
  language: z.literal("en"),
  entities: z.array(Entities$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    onFailure: "on_failure",
  });
});

export function piiRedactionPluginEnToJSON(
  piiRedactionPluginEn: PIIRedactionPluginEn,
): string {
  return JSON.stringify(
    PIIRedactionPluginEn$outboundSchema.parse(piiRedactionPluginEn),
  );
}
export function piiRedactionPluginEnFromJSON(
  jsonString: string,
): SafeParseResult<PIIRedactionPluginEn, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PIIRedactionPluginEn$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PIIRedactionPluginEn' from JSON`,
  );
}
