/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  Price,
  Price$inboundSchema,
  Price$Outbound,
  Price$outboundSchema,
} from "./price.js";

export type PricingVariant = {
  cacheRead?: Price | undefined;
  cacheWrite1h?: Price | undefined;
  cacheWrite5m?: Price | undefined;
  input?: Price | undefined;
  output?: Price | undefined;
  reasoning?: Price | undefined;
  when: string;
};

/** @internal */
export const PricingVariant$inboundSchema: z.ZodType<
  PricingVariant,
  z.ZodTypeDef,
  unknown
> = z.object({
  cache_read: Price$inboundSchema.optional(),
  cache_write_1h: Price$inboundSchema.optional(),
  cache_write_5m: Price$inboundSchema.optional(),
  input: Price$inboundSchema.optional(),
  output: Price$inboundSchema.optional(),
  reasoning: Price$inboundSchema.optional(),
  when: z.string(),
}).transform((v) => {
  return remap$(v, {
    "cache_read": "cacheRead",
    "cache_write_1h": "cacheWrite1h",
    "cache_write_5m": "cacheWrite5m",
  });
});
/** @internal */
export type PricingVariant$Outbound = {
  cache_read?: Price$Outbound | undefined;
  cache_write_1h?: Price$Outbound | undefined;
  cache_write_5m?: Price$Outbound | undefined;
  input?: Price$Outbound | undefined;
  output?: Price$Outbound | undefined;
  reasoning?: Price$Outbound | undefined;
  when: string;
};

/** @internal */
export const PricingVariant$outboundSchema: z.ZodType<
  PricingVariant$Outbound,
  z.ZodTypeDef,
  PricingVariant
> = z.object({
  cacheRead: Price$outboundSchema.optional(),
  cacheWrite1h: Price$outboundSchema.optional(),
  cacheWrite5m: Price$outboundSchema.optional(),
  input: Price$outboundSchema.optional(),
  output: Price$outboundSchema.optional(),
  reasoning: Price$outboundSchema.optional(),
  when: z.string(),
}).transform((v) => {
  return remap$(v, {
    cacheRead: "cache_read",
    cacheWrite1h: "cache_write_1h",
    cacheWrite5m: "cache_write_5m",
  });
});

export function pricingVariantToJSON(pricingVariant: PricingVariant): string {
  return JSON.stringify(PricingVariant$outboundSchema.parse(pricingVariant));
}
export function pricingVariantFromJSON(
  jsonString: string,
): SafeParseResult<PricingVariant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PricingVariant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PricingVariant' from JSON`,
  );
}
