/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Project = {
  projectId?: string | undefined;
  name?: string | undefined;
  key?: string | undefined;
  workspaceId?: string | undefined;
  isArchived?: boolean | undefined;
  isDefault?: boolean | undefined;
  teams?: Array<string> | undefined;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  createdById?: string | undefined;
  updatedById?: string | undefined;
};

/** @internal */
export const Project$inboundSchema: z.ZodType<Project, z.ZodTypeDef, unknown> =
  z.object({
    project_id: z.string().optional(),
    name: z.string().optional(),
    key: z.string().optional(),
    workspace_id: z.string().optional(),
    is_archived: z.boolean().optional(),
    is_default: z.boolean().optional(),
    teams: z.array(z.string()).optional(),
    created_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    updated_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    created_by_id: z.string().optional(),
    updated_by_id: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      "project_id": "projectId",
      "workspace_id": "workspaceId",
      "is_archived": "isArchived",
      "is_default": "isDefault",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
      "created_by_id": "createdById",
      "updated_by_id": "updatedById",
    });
  });

export function projectFromJSON(
  jsonString: string,
): SafeParseResult<Project, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Project$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Project' from JSON`,
  );
}
