/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const StatFileSystemFileResponseType = {
  File: "file",
  Dir: "dir",
  Symlink: "symlink",
  Other: "other",
} as const;
export type StatFileSystemFileResponseType = ClosedEnum<
  typeof StatFileSystemFileResponseType
>;

export type StatFileSystemFileResponse = {
  path: string;
  type: StatFileSystemFileResponseType;
  sizeBytes: string;
  /**
   * Permission bits in octal, for example 0644
   */
  mode: string;
  modified: string;
};

/** @internal */
export const StatFileSystemFileResponseType$inboundSchema: z.ZodNativeEnum<
  typeof StatFileSystemFileResponseType
> = z.nativeEnum(StatFileSystemFileResponseType);

/** @internal */
export const StatFileSystemFileResponse$inboundSchema: z.ZodType<
  StatFileSystemFileResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  path: z.string(),
  type: StatFileSystemFileResponseType$inboundSchema,
  size_bytes: z.string(),
  mode: z.string(),
  modified: z.string(),
}).transform((v) => {
  return remap$(v, {
    "size_bytes": "sizeBytes",
  });
});

export function statFileSystemFileResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatFileSystemFileResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatFileSystemFileResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatFileSystemFileResponse' from JSON`,
  );
}
