/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evalsContainsAny } from "../../funcs/evalsContainsAny.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EvalsContainsAnyRequestBody$inboundSchema.optional(),
};

export const tool$evalsContainsAny: ToolDefinition<typeof args> = {
  name: "evals-contains-any",
  description: `Run Contains Any Evaluator`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await evalsContainsAny(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
