/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { knowledgeUpdateDatasource } from "../../funcs/knowledgeUpdateDatasource.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateDatasourceRequest$inboundSchema,
};

export const tool$knowledgeUpdateDatasource: ToolDefinition<typeof args> = {
  name: "knowledge-update-datasource",
  description: `Update a datasource`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await knowledgeUpdateDatasource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
