/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { OrqError } from "./orqerror.js";

/**
 * Workspace ID is not found on the request
 */
export type PostV2FeedbackResponseResponseBodyData = {
  message: string;
};

/**
 * Workspace ID is not found on the request
 */
export class PostV2FeedbackResponseResponseBody extends OrqError {
  /** The original data that was passed to this error instance. */
  data$: PostV2FeedbackResponseResponseBodyData;

  constructor(
    err: PostV2FeedbackResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "PostV2FeedbackResponseResponseBody";
  }
}

/**
 * Bad Request
 */
export type PostV2FeedbackResponseBodyData = {
  message: string;
};

/**
 * Bad Request
 */
export class PostV2FeedbackResponseBody extends OrqError {
  /** The original data that was passed to this error instance. */
  data$: PostV2FeedbackResponseBodyData;

  constructor(
    err: PostV2FeedbackResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;

    this.name = "PostV2FeedbackResponseBody";
  }
}

/** @internal */
export const PostV2FeedbackResponseResponseBody$inboundSchema: z.ZodType<
  PostV2FeedbackResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostV2FeedbackResponseResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2FeedbackResponseBody$inboundSchema: z.ZodType<
  PostV2FeedbackResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostV2FeedbackResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
