/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type CreateMemoryRequest = {
  memoryStoreKey: string;
  createMemoryRequest: components.CreateMemoryRequest;
};

/** @internal */
export type CreateMemoryRequest$Outbound = {
  memory_store_key: string;
  CreateMemoryRequest: components.CreateMemoryRequest$Outbound;
};

/** @internal */
export const CreateMemoryRequest$outboundSchema: z.ZodType<
  CreateMemoryRequest$Outbound,
  z.ZodTypeDef,
  CreateMemoryRequest
> = z.object({
  memoryStoreKey: z.string(),
  createMemoryRequest: components.CreateMemoryRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    memoryStoreKey: "memory_store_key",
    createMemoryRequest: "CreateMemoryRequest",
  });
});

export function createMemoryRequestToJSON(
  createMemoryRequest: CreateMemoryRequest,
): string {
  return JSON.stringify(
    CreateMemoryRequest$outboundSchema.parse(createMemoryRequest),
  );
}
