/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetEvalVersionRequest = {
  id: string;
  versionId: string;
};

/** @internal */
export type GetEvalVersionRequest$Outbound = {
  id: string;
  version_id: string;
};

/** @internal */
export const GetEvalVersionRequest$outboundSchema: z.ZodType<
  GetEvalVersionRequest$Outbound,
  z.ZodTypeDef,
  GetEvalVersionRequest
> = z.object({
  id: z.string(),
  versionId: z.string(),
}).transform((v) => {
  return remap$(v, {
    versionId: "version_id",
  });
});

export function getEvalVersionRequestToJSON(
  getEvalVersionRequest: GetEvalVersionRequest,
): string {
  return JSON.stringify(
    GetEvalVersionRequest$outboundSchema.parse(getEvalVersionRequest),
  );
}
