/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type GetOneChunkRequest = {
  knowledgeId: string;
  datasourceId: string;
  chunkId: string;
};

/** @internal */
export type GetOneChunkRequest$Outbound = {
  knowledge_id: string;
  datasource_id: string;
  chunk_id: string;
};

/** @internal */
export const GetOneChunkRequest$outboundSchema: z.ZodType<
  GetOneChunkRequest$Outbound,
  z.ZodTypeDef,
  GetOneChunkRequest
> = z.object({
  knowledgeId: z.string(),
  datasourceId: z.string(),
  chunkId: z.string(),
}).transform((v) => {
  return remap$(v, {
    knowledgeId: "knowledge_id",
    datasourceId: "datasource_id",
    chunkId: "chunk_id",
  });
});

export function getOneChunkRequestToJSON(
  getOneChunkRequest: GetOneChunkRequest,
): string {
  return JSON.stringify(
    GetOneChunkRequest$outboundSchema.parse(getOneChunkRequest),
  );
}
