/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type ListWikisRequest = {
  limit?: number | undefined;
  startingAfter?: string | undefined;
  endingBefore?: string | undefined;
  repositoryKey?: string | undefined;
  branch?: string | undefined;
  factoryId?: string | undefined;
};

/** @internal */
export type ListWikisRequest$Outbound = {
  limit?: number | undefined;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  repository_key?: string | undefined;
  branch?: string | undefined;
  factory_id?: string | undefined;
};

/** @internal */
export const ListWikisRequest$outboundSchema: z.ZodType<
  ListWikisRequest$Outbound,
  z.ZodTypeDef,
  ListWikisRequest
> = z.object({
  limit: z.number().int().optional(),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
  repositoryKey: z.string().optional(),
  branch: z.string().optional(),
  factoryId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    startingAfter: "starting_after",
    endingBefore: "ending_before",
    repositoryKey: "repository_key",
    factoryId: "factory_id",
  });
});

export function listWikisRequestToJSON(
  listWikisRequest: ListWikisRequest,
): string {
  return JSON.stringify(
    ListWikisRequest$outboundSchema.parse(listWikisRequest),
  );
}
