/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type McpServerListRequest = {
  limit?: number | undefined;
  startingAfter?: string | undefined;
  endingBefore?: string | undefined;
  search?: string | undefined;
  status?: components.McpServerStatus | undefined;
};

/** @internal */
export type McpServerListRequest$Outbound = {
  limit?: number | undefined;
  starting_after?: string | undefined;
  ending_before?: string | undefined;
  search?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const McpServerListRequest$outboundSchema: z.ZodType<
  McpServerListRequest$Outbound,
  z.ZodTypeDef,
  McpServerListRequest
> = z.object({
  limit: z.number().int().optional(),
  startingAfter: z.string().optional(),
  endingBefore: z.string().optional(),
  search: z.string().optional(),
  status: components.McpServerStatus$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    startingAfter: "starting_after",
    endingBefore: "ending_before",
  });
});

export function mcpServerListRequestToJSON(
  mcpServerListRequest: McpServerListRequest,
): string {
  return JSON.stringify(
    McpServerListRequest$outboundSchema.parse(mcpServerListRequest),
  );
}
