/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ModelUpdateRequestBody = {
  displayName?: string | undefined;
  hasFunctions?: boolean | undefined;
  inputCost?: number | undefined;
  metadata?: components.ModelMetadata | undefined;
  modelType?: string | undefined;
  outputCost?: number | undefined;
  parameters?: Array<components.UpdateModelParameter> | undefined;
};

export type ModelUpdateRequest = {
  /**
   * The ID of the model
   */
  id: string;
  requestBody: ModelUpdateRequestBody;
};

/**
 * Model updated successfully
 */
export type ModelUpdateResponseBody = {
  configuration: components.ModelConfigurationResponse;
  created: Date;
  description: string | null;
  displayName: string;
  docsUrl: string | null;
  enabled: boolean;
  enabledForEndpoints: boolean;
  enabledForPlayground: boolean;
  hasCpuPricing: boolean;
  hasFunctions: boolean;
  id: string;
  inputCost: number | null;
  inputCurrency: string;
  isActive: boolean;
  metadata: components.ModelMetadata;
  modelDeveloper?: string | undefined;
  modelFamily?: string | undefined;
  modelId: string;
  modelType: string;
  outputCost: number | null;
  outputCurrency: string;
  owner: string;
  parameters: Array<components.ModelParameterDocument> | null;
  pricingUrl: string | null;
  provider: string;
  refId: string;
  updated: Date;
};

/** @internal */
export type ModelUpdateRequestBody$Outbound = {
  display_name?: string | undefined;
  has_functions?: boolean | undefined;
  input_cost?: number | undefined;
  metadata?: components.ModelMetadata$Outbound | undefined;
  model_type?: string | undefined;
  output_cost?: number | undefined;
  parameters?: Array<components.UpdateModelParameter$Outbound> | undefined;
};

/** @internal */
export const ModelUpdateRequestBody$outboundSchema: z.ZodType<
  ModelUpdateRequestBody$Outbound,
  z.ZodTypeDef,
  ModelUpdateRequestBody
> = z.object({
  displayName: z.string().optional(),
  hasFunctions: z.boolean().optional(),
  inputCost: z.number().optional(),
  metadata: components.ModelMetadata$outboundSchema.optional(),
  modelType: z.string().optional(),
  outputCost: z.number().optional(),
  parameters: z.array(components.UpdateModelParameter$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
    hasFunctions: "has_functions",
    inputCost: "input_cost",
    modelType: "model_type",
    outputCost: "output_cost",
  });
});

export function modelUpdateRequestBodyToJSON(
  modelUpdateRequestBody: ModelUpdateRequestBody,
): string {
  return JSON.stringify(
    ModelUpdateRequestBody$outboundSchema.parse(modelUpdateRequestBody),
  );
}

/** @internal */
export type ModelUpdateRequest$Outbound = {
  id: string;
  RequestBody: ModelUpdateRequestBody$Outbound;
};

/** @internal */
export const ModelUpdateRequest$outboundSchema: z.ZodType<
  ModelUpdateRequest$Outbound,
  z.ZodTypeDef,
  ModelUpdateRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => ModelUpdateRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function modelUpdateRequestToJSON(
  modelUpdateRequest: ModelUpdateRequest,
): string {
  return JSON.stringify(
    ModelUpdateRequest$outboundSchema.parse(modelUpdateRequest),
  );
}

/** @internal */
export const ModelUpdateResponseBody$inboundSchema: z.ZodType<
  ModelUpdateResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  configuration: components.ModelConfigurationResponse$inboundSchema,
  created: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  description: z.nullable(z.string()),
  display_name: z.string(),
  docs_url: z.nullable(z.string()),
  enabled: z.boolean(),
  enabled_for_endpoints: z.boolean(),
  enabled_for_playground: z.boolean(),
  has_cpu_pricing: z.boolean(),
  has_functions: z.boolean(),
  id: z.string(),
  input_cost: z.nullable(z.number()),
  input_currency: z.string(),
  is_active: z.boolean(),
  metadata: components.ModelMetadata$inboundSchema,
  model_developer: z.string().optional(),
  model_family: z.string().optional(),
  model_id: z.string(),
  model_type: z.string(),
  output_cost: z.nullable(z.number()),
  output_currency: z.string(),
  owner: z.string(),
  parameters: z.nullable(
    z.array(components.ModelParameterDocument$inboundSchema),
  ),
  pricing_url: z.nullable(z.string()),
  provider: z.string(),
  refId: z.string(),
  updated: z.string().datetime({ offset: true }).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
    "docs_url": "docsUrl",
    "enabled_for_endpoints": "enabledForEndpoints",
    "enabled_for_playground": "enabledForPlayground",
    "has_cpu_pricing": "hasCpuPricing",
    "has_functions": "hasFunctions",
    "input_cost": "inputCost",
    "input_currency": "inputCurrency",
    "is_active": "isActive",
    "model_developer": "modelDeveloper",
    "model_family": "modelFamily",
    "model_id": "modelId",
    "model_type": "modelType",
    "output_cost": "outputCost",
    "output_currency": "outputCurrency",
    "pricing_url": "pricingUrl",
  });
});

export function modelUpdateResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ModelUpdateResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelUpdateResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelUpdateResponseBody' from JSON`,
  );
}
