/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Headers = {
  /**
   * Header value. **Update behavior**: Provide empty string ("") to preserve existing encrypted value without re-entering credentials. Provide new value to rotate. Omit header entirely to remove.
   */
  value: string;
  encrypted?: boolean | undefined;
};

export type PostV2AgentsA2aRequestBody = {
  /**
   * Unique identifier for the agent
   */
  key: string;
  /**
   * Display name for the agent
   */
  displayName: string;
  /**
   * Description of the agent
   */
  description: string;
  /**
   * Project path for organizing the agent
   */
  path: string;
  /**
   * The A2A agent endpoint URL
   */
  agentUrl: string;
  /**
   * Optional explicit agent card URL (must be different from agent_url)
   */
  cardUrl?: string | undefined;
  /**
   * Authentication headers for the A2A agent
   */
  headers?: { [k: string]: Headers } | undefined;
};

export const PostV2AgentsA2aType = {
  A2a: "a2a",
  Internal: "internal",
} as const;
export type PostV2AgentsA2aType = ClosedEnum<typeof PostV2AgentsA2aType>;

export type PostV2AgentsA2aMetrics = {
  totalCost: number;
};

export type A2a = {
  agentUrl: string;
  cardUrl?: string | undefined;
  headers: { [k: string]: any };
  cachedCard?: any | undefined;
};

/**
 * A2A agent registered successfully
 */
export type PostV2AgentsA2aResponseBody = {
  id: string;
  type: PostV2AgentsA2aType;
  key: string;
  displayName: string;
  description: string;
  workspaceId: string;
  projectId: string;
  createdById?: string | null | undefined;
  updatedById?: string | null | undefined;
  role?: string | undefined;
  instructions?: string | undefined;
  status: string;
  path: string;
  metrics: PostV2AgentsA2aMetrics;
  memoryStores: Array<string>;
  teamOfAgents: Array<any>;
  created?: string | undefined;
  updated?: string | undefined;
  a2a?: A2a | undefined;
};

/** @internal */
export type Headers$Outbound = {
  value: string;
  encrypted: boolean;
};

/** @internal */
export const Headers$outboundSchema: z.ZodType<
  Headers$Outbound,
  z.ZodTypeDef,
  Headers
> = z.object({
  value: z.string(),
  encrypted: z.boolean().default(false),
});

export function headersToJSON(headers: Headers): string {
  return JSON.stringify(Headers$outboundSchema.parse(headers));
}

/** @internal */
export type PostV2AgentsA2aRequestBody$Outbound = {
  key: string;
  display_name: string;
  description: string;
  path: string;
  agent_url: string;
  card_url?: string | undefined;
  headers?: { [k: string]: Headers$Outbound } | undefined;
};

/** @internal */
export const PostV2AgentsA2aRequestBody$outboundSchema: z.ZodType<
  PostV2AgentsA2aRequestBody$Outbound,
  z.ZodTypeDef,
  PostV2AgentsA2aRequestBody
> = z.object({
  key: z.string(),
  displayName: z.string(),
  description: z.string(),
  path: z.string(),
  agentUrl: z.string(),
  cardUrl: z.string().optional(),
  headers: z.record(z.lazy(() => Headers$outboundSchema)).optional(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
    agentUrl: "agent_url",
    cardUrl: "card_url",
  });
});

export function postV2AgentsA2aRequestBodyToJSON(
  postV2AgentsA2aRequestBody: PostV2AgentsA2aRequestBody,
): string {
  return JSON.stringify(
    PostV2AgentsA2aRequestBody$outboundSchema.parse(postV2AgentsA2aRequestBody),
  );
}

/** @internal */
export const PostV2AgentsA2aType$inboundSchema: z.ZodNativeEnum<
  typeof PostV2AgentsA2aType
> = z.nativeEnum(PostV2AgentsA2aType);

/** @internal */
export const PostV2AgentsA2aMetrics$inboundSchema: z.ZodType<
  PostV2AgentsA2aMetrics,
  z.ZodTypeDef,
  unknown
> = z.object({
  total_cost: z.number(),
}).transform((v) => {
  return remap$(v, {
    "total_cost": "totalCost",
  });
});

export function postV2AgentsA2aMetricsFromJSON(
  jsonString: string,
): SafeParseResult<PostV2AgentsA2aMetrics, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2AgentsA2aMetrics$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2AgentsA2aMetrics' from JSON`,
  );
}

/** @internal */
export const A2a$inboundSchema: z.ZodType<A2a, z.ZodTypeDef, unknown> = z
  .object({
    agent_url: z.string(),
    card_url: z.string().optional(),
    headers: z.record(z.any()),
    cached_card: z.any().optional(),
  }).transform((v) => {
    return remap$(v, {
      "agent_url": "agentUrl",
      "card_url": "cardUrl",
      "cached_card": "cachedCard",
    });
  });

export function a2aFromJSON(
  jsonString: string,
): SafeParseResult<A2a, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => A2a$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'A2a' from JSON`,
  );
}

/** @internal */
export const PostV2AgentsA2aResponseBody$inboundSchema: z.ZodType<
  PostV2AgentsA2aResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string(),
  type: PostV2AgentsA2aType$inboundSchema,
  key: z.string(),
  display_name: z.string(),
  description: z.string(),
  workspace_id: z.string(),
  project_id: z.string(),
  created_by_id: z.nullable(z.string()).optional(),
  updated_by_id: z.nullable(z.string()).optional(),
  role: z.string().optional(),
  instructions: z.string().optional(),
  status: z.string(),
  path: z.string(),
  metrics: z.lazy(() => PostV2AgentsA2aMetrics$inboundSchema),
  memory_stores: z.array(z.string()),
  team_of_agents: z.array(z.any()),
  created: z.string().optional(),
  updated: z.string().optional(),
  a2a: z.lazy(() => A2a$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "display_name": "displayName",
    "workspace_id": "workspaceId",
    "project_id": "projectId",
    "created_by_id": "createdById",
    "updated_by_id": "updatedById",
    "memory_stores": "memoryStores",
    "team_of_agents": "teamOfAgents",
  });
});

export function postV2AgentsA2aResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostV2AgentsA2aResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2AgentsA2aResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2AgentsA2aResponseBody' from JSON`,
  );
}
