/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type SkillUpdateRequest = {
  skillId: string;
  updateSkillRequest: components.UpdateSkillRequest;
};

/** @internal */
export type SkillUpdateRequest$Outbound = {
  skill_id: string;
  UpdateSkillRequest: components.UpdateSkillRequest$Outbound;
};

/** @internal */
export const SkillUpdateRequest$outboundSchema: z.ZodType<
  SkillUpdateRequest$Outbound,
  z.ZodTypeDef,
  SkillUpdateRequest
> = z.object({
  skillId: z.string(),
  updateSkillRequest: components.UpdateSkillRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    skillId: "skill_id",
    updateSkillRequest: "UpdateSkillRequest",
  });
});

export function skillUpdateRequestToJSON(
  skillUpdateRequest: SkillUpdateRequest,
): string {
  return JSON.stringify(
    SkillUpdateRequest$outboundSchema.parse(skillUpdateRequest),
  );
}
