/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpToolsetsCreate } from "../funcs/mcpToolsetsCreate.js";
import { mcpToolsetsDelete } from "../funcs/mcpToolsetsDelete.js";
import { mcpToolsetsGet } from "../funcs/mcpToolsetsGet.js";
import { mcpToolsetsList } from "../funcs/mcpToolsetsList.js";
import { mcpToolsetsUpdate } from "../funcs/mcpToolsetsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class McpToolsets extends ClientSDK {
  /**
   * List MCP toolsets
   *
   * @remarks
   * Returns a paginated list of MCP toolsets in the workspace.
   */
  async list(
    request?: operations.McpToolsetListRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.ListMcpToolsetsResponse> {
    return unwrapAsync(mcpToolsetsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an MCP toolset
   *
   * @remarks
   * Creates a named, project-scoped collection of individual tools drawn from MCP servers. Toolsets can be assigned to API keys to narrow the tools a key may see and call.
   */
  async create(
    request: components.CreateMcpToolsetRequest,
    options?: RequestOptions,
  ): Promise<components.CreateMcpToolsetResponse> {
    return unwrapAsync(mcpToolsetsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Retrieve an MCP toolset
   *
   * @remarks
   * Retrieves the details of an existing MCP toolset by its unique ID.
   */
  async get(
    request: operations.McpToolsetGetRequest,
    options?: RequestOptions,
  ): Promise<components.GetMcpToolsetResponse> {
    return unwrapAsync(mcpToolsetsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete an MCP toolset
   *
   * @remarks
   * Deletes an MCP toolset from the workspace. The response body is empty when the delete succeeds.
   */
  async delete(
    request: operations.McpToolsetDeleteRequest,
    options?: RequestOptions,
  ): Promise<components.DeleteMcpToolsetResponse> {
    return unwrapAsync(mcpToolsetsDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Update an MCP toolset
   *
   * @remarks
   * Updates mutable fields of an existing MCP toolset. Omitted optional fields keep their current values.
   */
  async update(
    request: operations.McpToolsetUpdateRequest,
    options?: RequestOptions,
  ): Promise<components.UpdateMcpToolsetResponse> {
    return unwrapAsync(mcpToolsetsUpdate(
      this,
      request,
      options,
    ));
  }
}
