workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    orq-ai-node:
        inputs:
            - location: ./openapi.yaml
    orq-ai-prerelease-node:
        inputs:
            - location: ./openapi-prerelease.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-ai-prerelease-node
targets:
    orq-ai-node:
        target: typescript
        source: orq-ai-node
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-ai-node-typescript-code-samples
            blocking: false
    orq-ai-prerelease-node:
        target: typescript
        source: orq-ai-prerelease-node
        output: ./packages/orq-rc
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-ai-prerelease-node-typescript-code-samples
            blocking: false
