workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    orq-node:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-node
    orq-prerelease-node:
        inputs:
            - location: ./openapi-prerelease.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-prerelease-node
targets:
    orq-node:
        target: typescript
        source: orq-node
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-node-code-samples
            blocking: false
    orq-prerelease-node:
        target: typescript
        source: orq-prerelease-node
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-prerelease-node-code-samples
            blocking: false
