/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateAnnotationQueueRequestBody = {
  /**
   * The display name of the annotation queue
   */
  displayName: string;
  /**
   * The description of the annotation queue
   */
  description: string;
  /**
   * The project ID to link this annotation queue to
   */
  projectId: string;
};

export type CreateAnnotationQueueMetadata = {
  /**
   * The number of items in the annotation queue
   */
  itemsCount: number;
};

/**
 * Annotation queue created
 */
export type CreateAnnotationQueueResponseBody = {
  /**
   * The unique identifier of the annotation queue
   */
  id: string;
  /**
   * The display name of the annotation queue
   */
  displayName: string;
  /**
   * The description of the annotation queue
   */
  description: string;
  /**
   * The unique identifier of the workspace it belongs to
   */
  workspaceId: string;
  /**
   * The project ID. When set, human reviews are resolved from the project automatically
   */
  projectId?: string | undefined;
  /**
   * Legacy: manually selected human review IDs. Used only when project_id is not set
   */
  humanReviewIds: Array<string>;
  metadata: CreateAnnotationQueueMetadata;
  /**
   * The id of the user who created the resource
   */
  createdById?: string | null | undefined;
  /**
   * The id of the user who last updated the resource
   */
  updatedById?: string | null | undefined;
  /**
   * The date and time the resource was created
   */
  created?: Date | undefined;
  /**
   * The date and time the resource was last updated
   */
  updated: Date;
};

/** @internal */
export type CreateAnnotationQueueRequestBody$Outbound = {
  display_name: string;
  description: string;
  project_id: string;
};

/** @internal */
export const CreateAnnotationQueueRequestBody$outboundSchema: z.ZodType<
  CreateAnnotationQueueRequestBody$Outbound,
  z.ZodTypeDef,
  CreateAnnotationQueueRequestBody
> = z.object({
  displayName: z.string(),
  description: z.string(),
  projectId: z.string(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
    projectId: "project_id",
  });
});

export function createAnnotationQueueRequestBodyToJSON(
  createAnnotationQueueRequestBody: CreateAnnotationQueueRequestBody,
): string {
  return JSON.stringify(
    CreateAnnotationQueueRequestBody$outboundSchema.parse(
      createAnnotationQueueRequestBody,
    ),
  );
}

/** @internal */
export const CreateAnnotationQueueMetadata$inboundSchema: z.ZodType<
  CreateAnnotationQueueMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  items_count: z.number(),
}).transform((v) => {
  return remap$(v, {
    "items_count": "itemsCount",
  });
});

export function createAnnotationQueueMetadataFromJSON(
  jsonString: string,
): SafeParseResult<CreateAnnotationQueueMetadata, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAnnotationQueueMetadata$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAnnotationQueueMetadata' from JSON`,
  );
}

/** @internal */
export const CreateAnnotationQueueResponseBody$inboundSchema: z.ZodType<
  CreateAnnotationQueueResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string(),
  display_name: z.string(),
  description: z.string(),
  workspace_id: z.string(),
  project_id: z.string().optional(),
  human_review_ids: z.array(z.string()),
  metadata: z.lazy(() => CreateAnnotationQueueMetadata$inboundSchema),
  created_by_id: z.nullable(z.string()).optional(),
  updated_by_id: z.nullable(z.string()).optional(),
  created: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated: z.string().datetime({ offset: true }).default(
    "2026-08-13T20:37:21.768Z",
  ).transform(v => new Date(v)),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "display_name": "displayName",
    "workspace_id": "workspaceId",
    "project_id": "projectId",
    "human_review_ids": "humanReviewIds",
    "created_by_id": "createdById",
    "updated_by_id": "updatedById",
  });
});

export function createAnnotationQueueResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateAnnotationQueueResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAnnotationQueueResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAnnotationQueueResponseBody' from JSON`,
  );
}
