/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type EvalsRagasNoiseSensitivityRequestBody = {
  /**
   * Latest user message
   */
  query: string;
  /**
   * The generated response from the model
   */
  output: string;
  model: string;
  /**
   * The ground truth answer to evaluate noise sensitivity against
   */
  reference: string;
  /**
   * Knowledge base retrievals that may contain irrelevant information
   */
  retrievals?: Array<string> | undefined;
};

/**
 * Returns the noise sensitivity evaluation result
 */
export type EvalsRagasNoiseSensitivityResponseBody = {
  value: number | null;
};

/** @internal */
export const EvalsRagasNoiseSensitivityRequestBody$inboundSchema: z.ZodType<
  EvalsRagasNoiseSensitivityRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  query: z.string(),
  output: z.string(),
  model: z.string(),
  reference: z.string(),
  retrievals: z.array(z.string()).optional(),
});

/** @internal */
export type EvalsRagasNoiseSensitivityRequestBody$Outbound = {
  query: string;
  output: string;
  model: string;
  reference: string;
  retrievals?: Array<string> | undefined;
};

/** @internal */
export const EvalsRagasNoiseSensitivityRequestBody$outboundSchema: z.ZodType<
  EvalsRagasNoiseSensitivityRequestBody$Outbound,
  z.ZodTypeDef,
  EvalsRagasNoiseSensitivityRequestBody
> = z.object({
  query: z.string(),
  output: z.string(),
  model: z.string(),
  reference: z.string(),
  retrievals: z.array(z.string()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EvalsRagasNoiseSensitivityRequestBody$ {
  /** @deprecated use `EvalsRagasNoiseSensitivityRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    EvalsRagasNoiseSensitivityRequestBody$inboundSchema;
  /** @deprecated use `EvalsRagasNoiseSensitivityRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    EvalsRagasNoiseSensitivityRequestBody$outboundSchema;
  /** @deprecated use `EvalsRagasNoiseSensitivityRequestBody$Outbound` instead. */
  export type Outbound = EvalsRagasNoiseSensitivityRequestBody$Outbound;
}

export function evalsRagasNoiseSensitivityRequestBodyToJSON(
  evalsRagasNoiseSensitivityRequestBody: EvalsRagasNoiseSensitivityRequestBody,
): string {
  return JSON.stringify(
    EvalsRagasNoiseSensitivityRequestBody$outboundSchema.parse(
      evalsRagasNoiseSensitivityRequestBody,
    ),
  );
}

export function evalsRagasNoiseSensitivityRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<EvalsRagasNoiseSensitivityRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EvalsRagasNoiseSensitivityRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvalsRagasNoiseSensitivityRequestBody' from JSON`,
  );
}

/** @internal */
export const EvalsRagasNoiseSensitivityResponseBody$inboundSchema: z.ZodType<
  EvalsRagasNoiseSensitivityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  value: z.nullable(z.number()),
});

/** @internal */
export type EvalsRagasNoiseSensitivityResponseBody$Outbound = {
  value: number | null;
};

/** @internal */
export const EvalsRagasNoiseSensitivityResponseBody$outboundSchema: z.ZodType<
  EvalsRagasNoiseSensitivityResponseBody$Outbound,
  z.ZodTypeDef,
  EvalsRagasNoiseSensitivityResponseBody
> = z.object({
  value: z.nullable(z.number()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EvalsRagasNoiseSensitivityResponseBody$ {
  /** @deprecated use `EvalsRagasNoiseSensitivityResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    EvalsRagasNoiseSensitivityResponseBody$inboundSchema;
  /** @deprecated use `EvalsRagasNoiseSensitivityResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    EvalsRagasNoiseSensitivityResponseBody$outboundSchema;
  /** @deprecated use `EvalsRagasNoiseSensitivityResponseBody$Outbound` instead. */
  export type Outbound = EvalsRagasNoiseSensitivityResponseBody$Outbound;
}

export function evalsRagasNoiseSensitivityResponseBodyToJSON(
  evalsRagasNoiseSensitivityResponseBody:
    EvalsRagasNoiseSensitivityResponseBody,
): string {
  return JSON.stringify(
    EvalsRagasNoiseSensitivityResponseBody$outboundSchema.parse(
      evalsRagasNoiseSensitivityResponseBody,
    ),
  );
}

export function evalsRagasNoiseSensitivityResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<EvalsRagasNoiseSensitivityResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      EvalsRagasNoiseSensitivityResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvalsRagasNoiseSensitivityResponseBody' from JSON`,
  );
}
