/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type NotifierUpdateRequest = {
  notifierId: string;
  updateNotifierRequest: components.UpdateNotifierRequest;
};

/** @internal */
export type NotifierUpdateRequest$Outbound = {
  notifier_id: string;
  UpdateNotifierRequest: components.UpdateNotifierRequest$Outbound;
};

/** @internal */
export const NotifierUpdateRequest$outboundSchema: z.ZodType<
  NotifierUpdateRequest$Outbound,
  z.ZodTypeDef,
  NotifierUpdateRequest
> = z.object({
  notifierId: z.string(),
  updateNotifierRequest: components.UpdateNotifierRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    notifierId: "notifier_id",
    updateNotifierRequest: "UpdateNotifierRequest",
  });
});

export function notifierUpdateRequestToJSON(
  notifierUpdateRequest: NotifierUpdateRequest,
): string {
  return JSON.stringify(
    NotifierUpdateRequest$outboundSchema.parse(notifierUpdateRequest),
  );
}
