/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateFileSystemRequest = {
  fileSystemKey: string;
  updateFileSystemRequest: components.UpdateFileSystemRequest;
};

/** @internal */
export type UpdateFileSystemRequest$Outbound = {
  file_system_key: string;
  UpdateFileSystemRequest: components.UpdateFileSystemRequest$Outbound;
};

/** @internal */
export const UpdateFileSystemRequest$outboundSchema: z.ZodType<
  UpdateFileSystemRequest$Outbound,
  z.ZodTypeDef,
  UpdateFileSystemRequest
> = z.object({
  fileSystemKey: z.string(),
  updateFileSystemRequest: components.UpdateFileSystemRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    fileSystemKey: "file_system_key",
    updateFileSystemRequest: "UpdateFileSystemRequest",
  });
});

export function updateFileSystemRequestToJSON(
  updateFileSystemRequest: UpdateFileSystemRequest,
): string {
  return JSON.stringify(
    UpdateFileSystemRequest$outboundSchema.parse(updateFileSystemRequest),
  );
}
