/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type WorkspaceGetRequest = {
  key: string;
};

/** @internal */
export type WorkspaceGetRequest$Outbound = {
  key: string;
};

/** @internal */
export const WorkspaceGetRequest$outboundSchema: z.ZodType<
  WorkspaceGetRequest$Outbound,
  z.ZodTypeDef,
  WorkspaceGetRequest
> = z.object({
  key: z.string(),
});

export function workspaceGetRequestToJSON(
  workspaceGetRequest: WorkspaceGetRequest,
): string {
  return JSON.stringify(
    WorkspaceGetRequest$outboundSchema.parse(workspaceGetRequest),
  );
}
