/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mcpSessionsList } from "../funcs/mcpSessionsList.js";
import { mcpSessionsRevoke } from "../funcs/mcpSessionsRevoke.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class McpSessions extends ClientSDK {
  /**
   * List MCP sessions
   *
   * @remarks
   * Returns a paginated list of per-user OAuth sessions for MCP gateways.
   */
  async list(
    request?: operations.McpSessionListRequest | undefined,
    options?: RequestOptions,
  ): Promise<components.ListMcpSessionsResponse> {
    return unwrapAsync(mcpSessionsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Revoke an MCP session
   *
   * @remarks
   * Revokes a per-user OAuth session, invalidating the stored upstream token.
   */
  async revoke(
    request: operations.McpSessionRevokeRequest,
    options?: RequestOptions,
  ): Promise<components.RevokeMcpSessionResponse> {
    return unwrapAsync(mcpSessionsRevoke(
      this,
      request,
      options,
    ));
  }
}
