/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { routerModerationsCreate } from "../funcs/routerModerationsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Moderations extends ClientSDK {
  /**
   * Create moderation
   */
  async create(
    request: operations.CreateModerationRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateModerationResponseBody> {
    return unwrapAsync(routerModerationsCreate(
      this,
      request,
      options,
    ));
  }
}
