/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DataPart,
  DataPart$inboundSchema,
  DataPart$Outbound,
  DataPart$outboundSchema,
} from "./datapart.js";
import {
  FilePart,
  FilePart$inboundSchema,
  FilePart$Outbound,
  FilePart$outboundSchema,
} from "./filepart.js";
import {
  TextPart,
  TextPart$inboundSchema,
  TextPart$Outbound,
  TextPart$outboundSchema,
} from "./textpart.js";
import {
  ToolCallPart,
  ToolCallPart$inboundSchema,
  ToolCallPart$Outbound,
  ToolCallPart$outboundSchema,
} from "./toolcallpart.js";
import {
  ToolResultPart,
  ToolResultPart$inboundSchema,
  ToolResultPart$Outbound,
  ToolResultPart$outboundSchema,
} from "./toolresultpart.js";

export const AgentMessageCreatedStreamingEventRole = {
  User: "user",
  Tool: "tool",
} as const;
export type AgentMessageCreatedStreamingEventRole = ClosedEnum<
  typeof AgentMessageCreatedStreamingEventRole
>;

export type AgentMessageCreatedStreamingEventParts =
  | TextPart
  | DataPart
  | FilePart
  | ToolCallPart
  | ToolResultPart;

export type Message = {
  messageId?: string | undefined;
  role: AgentMessageCreatedStreamingEventRole;
  parts: Array<TextPart | DataPart | FilePart | ToolCallPart | ToolResultPart>;
  metadata?: { [k: string]: any } | undefined;
};

export type AgentMessageCreatedStreamingEventData = {
  workflowRunId: string;
  spanId: string;
  parentId: string;
  message: Array<Message>;
};

/**
 * Emitted when a new message is added to the conversation. Contains the message content, workflow run ID, and span context for tracing.
 */
export type AgentMessageCreatedStreamingEvent = {
  type: "event.agents.message-created";
  /**
   * ISO timestamp of the event
   */
  timestamp: string;
  data: AgentMessageCreatedStreamingEventData;
};

/** @internal */
export const AgentMessageCreatedStreamingEventRole$inboundSchema:
  z.ZodNativeEnum<typeof AgentMessageCreatedStreamingEventRole> = z.nativeEnum(
    AgentMessageCreatedStreamingEventRole,
  );
/** @internal */
export const AgentMessageCreatedStreamingEventRole$outboundSchema:
  z.ZodNativeEnum<typeof AgentMessageCreatedStreamingEventRole> =
    AgentMessageCreatedStreamingEventRole$inboundSchema;

/** @internal */
export const AgentMessageCreatedStreamingEventParts$inboundSchema: z.ZodType<
  AgentMessageCreatedStreamingEventParts,
  z.ZodTypeDef,
  unknown
> = z.union([
  TextPart$inboundSchema,
  DataPart$inboundSchema,
  FilePart$inboundSchema,
  ToolCallPart$inboundSchema,
  ToolResultPart$inboundSchema,
]);
/** @internal */
export type AgentMessageCreatedStreamingEventParts$Outbound =
  | TextPart$Outbound
  | DataPart$Outbound
  | FilePart$Outbound
  | ToolCallPart$Outbound
  | ToolResultPart$Outbound;

/** @internal */
export const AgentMessageCreatedStreamingEventParts$outboundSchema: z.ZodType<
  AgentMessageCreatedStreamingEventParts$Outbound,
  z.ZodTypeDef,
  AgentMessageCreatedStreamingEventParts
> = z.union([
  TextPart$outboundSchema,
  DataPart$outboundSchema,
  FilePart$outboundSchema,
  ToolCallPart$outboundSchema,
  ToolResultPart$outboundSchema,
]);

export function agentMessageCreatedStreamingEventPartsToJSON(
  agentMessageCreatedStreamingEventParts:
    AgentMessageCreatedStreamingEventParts,
): string {
  return JSON.stringify(
    AgentMessageCreatedStreamingEventParts$outboundSchema.parse(
      agentMessageCreatedStreamingEventParts,
    ),
  );
}
export function agentMessageCreatedStreamingEventPartsFromJSON(
  jsonString: string,
): SafeParseResult<AgentMessageCreatedStreamingEventParts, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AgentMessageCreatedStreamingEventParts$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentMessageCreatedStreamingEventParts' from JSON`,
  );
}

/** @internal */
export const Message$inboundSchema: z.ZodType<Message, z.ZodTypeDef, unknown> =
  z.object({
    messageId: z.string().optional(),
    role: AgentMessageCreatedStreamingEventRole$inboundSchema,
    parts: z.array(
      z.union([
        TextPart$inboundSchema,
        DataPart$inboundSchema,
        FilePart$inboundSchema,
        ToolCallPart$inboundSchema,
        ToolResultPart$inboundSchema,
      ]),
    ),
    metadata: z.record(z.any()).optional(),
  });
/** @internal */
export type Message$Outbound = {
  messageId?: string | undefined;
  role: string;
  parts: Array<
    | TextPart$Outbound
    | DataPart$Outbound
    | FilePart$Outbound
    | ToolCallPart$Outbound
    | ToolResultPart$Outbound
  >;
  metadata?: { [k: string]: any } | undefined;
};

/** @internal */
export const Message$outboundSchema: z.ZodType<
  Message$Outbound,
  z.ZodTypeDef,
  Message
> = z.object({
  messageId: z.string().optional(),
  role: AgentMessageCreatedStreamingEventRole$outboundSchema,
  parts: z.array(
    z.union([
      TextPart$outboundSchema,
      DataPart$outboundSchema,
      FilePart$outboundSchema,
      ToolCallPart$outboundSchema,
      ToolResultPart$outboundSchema,
    ]),
  ),
  metadata: z.record(z.any()).optional(),
});

export function messageToJSON(message: Message): string {
  return JSON.stringify(Message$outboundSchema.parse(message));
}
export function messageFromJSON(
  jsonString: string,
): SafeParseResult<Message, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Message$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Message' from JSON`,
  );
}

/** @internal */
export const AgentMessageCreatedStreamingEventData$inboundSchema: z.ZodType<
  AgentMessageCreatedStreamingEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  workflowRunId: z.string(),
  spanId: z.string(),
  parentId: z.string(),
  message: z.array(z.lazy(() => Message$inboundSchema)),
});
/** @internal */
export type AgentMessageCreatedStreamingEventData$Outbound = {
  workflowRunId: string;
  spanId: string;
  parentId: string;
  message: Array<Message$Outbound>;
};

/** @internal */
export const AgentMessageCreatedStreamingEventData$outboundSchema: z.ZodType<
  AgentMessageCreatedStreamingEventData$Outbound,
  z.ZodTypeDef,
  AgentMessageCreatedStreamingEventData
> = z.object({
  workflowRunId: z.string(),
  spanId: z.string(),
  parentId: z.string(),
  message: z.array(z.lazy(() => Message$outboundSchema)),
});

export function agentMessageCreatedStreamingEventDataToJSON(
  agentMessageCreatedStreamingEventData: AgentMessageCreatedStreamingEventData,
): string {
  return JSON.stringify(
    AgentMessageCreatedStreamingEventData$outboundSchema.parse(
      agentMessageCreatedStreamingEventData,
    ),
  );
}
export function agentMessageCreatedStreamingEventDataFromJSON(
  jsonString: string,
): SafeParseResult<AgentMessageCreatedStreamingEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      AgentMessageCreatedStreamingEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentMessageCreatedStreamingEventData' from JSON`,
  );
}

/** @internal */
export const AgentMessageCreatedStreamingEvent$inboundSchema: z.ZodType<
  AgentMessageCreatedStreamingEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("event.agents.message-created"),
  timestamp: z.string(),
  data: z.lazy(() => AgentMessageCreatedStreamingEventData$inboundSchema),
});
/** @internal */
export type AgentMessageCreatedStreamingEvent$Outbound = {
  type: "event.agents.message-created";
  timestamp: string;
  data: AgentMessageCreatedStreamingEventData$Outbound;
};

/** @internal */
export const AgentMessageCreatedStreamingEvent$outboundSchema: z.ZodType<
  AgentMessageCreatedStreamingEvent$Outbound,
  z.ZodTypeDef,
  AgentMessageCreatedStreamingEvent
> = z.object({
  type: z.literal("event.agents.message-created"),
  timestamp: z.string(),
  data: z.lazy(() => AgentMessageCreatedStreamingEventData$outboundSchema),
});

export function agentMessageCreatedStreamingEventToJSON(
  agentMessageCreatedStreamingEvent: AgentMessageCreatedStreamingEvent,
): string {
  return JSON.stringify(
    AgentMessageCreatedStreamingEvent$outboundSchema.parse(
      agentMessageCreatedStreamingEvent,
    ),
  );
}
export function agentMessageCreatedStreamingEventFromJSON(
  jsonString: string,
): SafeParseResult<AgentMessageCreatedStreamingEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AgentMessageCreatedStreamingEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AgentMessageCreatedStreamingEvent' from JSON`,
  );
}
