/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Config = {
  allowFork: boolean;
  allowVersionPin: boolean;
  autoGrantNewProjects: boolean;
  mode: string;
  projectIds?: Array<string> | null | undefined;
};

/** @internal */
export const Config$inboundSchema: z.ZodType<Config, z.ZodTypeDef, unknown> = z
  .object({
    allow_fork: z.boolean(),
    allow_version_pin: z.boolean(),
    auto_grant_new_projects: z.boolean(),
    mode: z.string(),
    project_ids: z.nullable(z.array(z.string())).optional(),
  }).transform((v) => {
    return remap$(v, {
      "allow_fork": "allowFork",
      "allow_version_pin": "allowVersionPin",
      "auto_grant_new_projects": "autoGrantNewProjects",
      "project_ids": "projectIds",
    });
  });

export function configFromJSON(
  jsonString: string,
): SafeParseResult<Config, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Config$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Config' from JSON`,
  );
}
