/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { SmartRouter, SmartRouter$inboundSchema } from "./smartrouter.js";

export type CreateSmartRouterResponse = {
  smartRouter: SmartRouter;
};

/** @internal */
export const CreateSmartRouterResponse$inboundSchema: z.ZodType<
  CreateSmartRouterResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  smart_router: SmartRouter$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "smart_router": "smartRouter",
  });
});

export function createSmartRouterResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateSmartRouterResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateSmartRouterResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateSmartRouterResponse' from JSON`,
  );
}
