/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { McpToolset, McpToolset$inboundSchema } from "./mcptoolset.js";

export type CreateMcpToolsetResponse = {
  mcpToolset?: McpToolset | undefined;
};

/** @internal */
export const CreateMcpToolsetResponse$inboundSchema: z.ZodType<
  CreateMcpToolsetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  mcp_toolset: McpToolset$inboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    "mcp_toolset": "mcpToolset",
  });
});

export function createMcpToolsetResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateMcpToolsetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateMcpToolsetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateMcpToolsetResponse' from JSON`,
  );
}
