/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { ApiKey, ApiKey$inboundSchema } from "./apikey.js";

export type CreateApiKeyResponse = {
  /**
   * Newly minted api-key record.
   */
  apiKey?: ApiKey | undefined;
  /**
   * Raw bearer token in the form `sk-orq-<api_key_id>-<secret>`.
   *
   * @remarks
   *  Returned ONCE; the API never exposes this value again. Clients
   *  must persist it immediately on receipt.
   */
  token?: string | undefined;
};

/** @internal */
export const CreateApiKeyResponse$inboundSchema: z.ZodType<
  CreateApiKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  api_key: ApiKey$inboundSchema.optional(),
  token: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "api_key": "apiKey",
  });
});

export function createApiKeyResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyResponse' from JSON`,
  );
}
