/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";

export type CreateDatasetRequest = {
  /**
   * Human-readable dataset name.
   */
  displayName: string;
  /**
   * Project path where the dataset should be stored, in the format `project/folder/subfolder`. With a project-scoped API key the path is relative to that project. Omit to use the API key project or the workspace default project.
   */
  path?: string | undefined;
};

/** @internal */
export type CreateDatasetRequest$Outbound = {
  display_name: string;
  path?: string | undefined;
};

/** @internal */
export const CreateDatasetRequest$outboundSchema: z.ZodType<
  CreateDatasetRequest$Outbound,
  z.ZodTypeDef,
  CreateDatasetRequest
> = z.object({
  displayName: z.string(),
  path: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
  });
});

export function createDatasetRequestToJSON(
  createDatasetRequest: CreateDatasetRequest,
): string {
  return JSON.stringify(
    CreateDatasetRequest$outboundSchema.parse(createDatasetRequest),
  );
}
