/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeletePersonResponse = {};

/** @internal */
export const DeletePersonResponse$inboundSchema: z.ZodType<
  DeletePersonResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function deletePersonResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeletePersonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeletePersonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeletePersonResponse' from JSON`,
  );
}
