/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Logical group the entry belongs to.
 */
export const Group = {
  DomainGroupUnspecified: "DOMAIN_GROUP_UNSPECIFIED",
  DomainGroupWorkspaceAdmin: "DOMAIN_GROUP_WORKSPACE_ADMIN",
  DomainGroupPlatform: "DOMAIN_GROUP_PLATFORM",
  DomainGroupGateway: "DOMAIN_GROUP_GATEWAY",
} as const;
/**
 * Logical group the entry belongs to.
 */
export type Group = ClosedEnum<typeof Group>;

export type Domain = {
  /**
   * Project scopes this domain may be granted under.
   */
  allowedScopes: Array<string> | null;
  /**
   * Human-readable label.
   */
  displayName: string;
  /**
   * Additional verbs granted only with write access.
   */
  extraWriteVerbs: Array<string> | null;
  /**
   * Logical group the entry belongs to.
   */
  group: Group;
  /**
   * Stable domain identifier, used as the key in access and as the verb prefix in resolved permissions.
   */
  id: string;
  /**
   * Whether the domain can be granted read access.
   */
  readable: boolean;
  /**
   * Whether the domain can be granted write access.
   */
  writable: boolean;
};

/** @internal */
export const Group$inboundSchema: z.ZodNativeEnum<typeof Group> = z.nativeEnum(
  Group,
);

/** @internal */
export const Domain$inboundSchema: z.ZodType<Domain, z.ZodTypeDef, unknown> = z
  .object({
    allowed_scopes: z.nullable(z.array(z.string())),
    display_name: z.string(),
    extra_write_verbs: z.nullable(z.array(z.string())),
    group: Group$inboundSchema,
    id: z.string(),
    readable: z.boolean(),
    writable: z.boolean(),
  }).transform((v) => {
    return remap$(v, {
      "allowed_scopes": "allowedScopes",
      "display_name": "displayName",
      "extra_write_verbs": "extraWriteVerbs",
    });
  });

export function domainFromJSON(
  jsonString: string,
): SafeParseResult<Domain, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Domain$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Domain' from JSON`,
  );
}
