/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ThirtyTwo = {
  type: "grammar_diversity";
};

export type ThirtyOne = {
  type: "lexical_repetition";
};

export type Thirty = {
  type: "sentences_count";
};

export type TwentyNine = {
  type: "words_count";
};

export type TwentyEight = {
  type: "gse_english_level";
};

export type TwentySeven = {
  type: "flesch_reading_ease";
};

export type TwentySix = {
  type: "most_repeated_words";
};

export type TwentyFive = {
  type: "keywords_match";
  keywords: Array<string>;
};

export type TwentyFour = {
  type: "levenshtein_distance";
};

export type TwentyThree = {
  type: "cosine_similarity";
};

export type TwentyTwo = {
  type: "meteor_score";
};

export type TwentyOne = {
  type: "rouge_n";
};

export type Twenty = {
  type: "bleu_score";
};

export type Nineteen = {
  type: "bert_score";
};

export type Eighteen = {
  type: "moderations_google";
};

export type Seventeen = {
  type: "moderations_openai";
};

export type Sixteen = {
  type: "is_valid_json";
};

export type Fifteen = {
  type: "regex";
  pattern: string;
};

export type Fourteen = {
  type: "one_line";
};

export type Thirteen = {
  type: "length_greater_than";
  value: number;
};

export type Twelve = {
  type: "length_between";
  min: number;
  max: number;
};

export type Eleven = {
  type: "length_less_than";
  value: number;
};

export type Ten = {
  type: "exact_match";
};

export type Nine = {
  type: "ends_with";
  value: string;
};

export type Eight = {
  type: "start_with";
  value: string;
};

export type Seven = {
  type: "contains_valid_link";
};

export type Six = {
  type: "contains_url";
};

export type Five = {
  type: "contains_email";
};

export type Four = {
  type: "contains_any";
  keywords: Array<string>;
};

export type Three = {
  type: "contains_all";
  keywords: Array<string>;
};

export type Two = {
  type: "contains_none";
  keywords: Array<string>;
};

export type One = {
  type: "contains";
  value: string;
};

export type FunctionParams =
  | One
  | Two
  | Three
  | Four
  | Five
  | Six
  | Seven
  | Eight
  | Nine
  | Ten
  | Eleven
  | Twelve
  | Thirteen
  | Fourteen
  | Fifteen
  | Sixteen
  | Seventeen
  | Eighteen
  | Nineteen
  | Twenty
  | TwentyOne
  | TwentyTwo
  | TwentyThree
  | TwentyFour
  | TwentyFive
  | TwentySix
  | TwentySeven
  | TwentyEight
  | TwentyNine
  | Thirty
  | ThirtyOne
  | ThirtyTwo;

export type EvaluatorResponseFunction = {
  id: string;
  description: string;
  created: string;
  updated: string;
  updatedById?: string | null | undefined;
  guardrailConfig?: any | undefined;
  type: "function_eval";
  functionParams:
    | One
    | Two
    | Three
    | Four
    | Five
    | Six
    | Seven
    | Eight
    | Nine
    | Ten
    | Eleven
    | Twelve
    | Thirteen
    | Fourteen
    | Fifteen
    | Sixteen
    | Seventeen
    | Eighteen
    | Nineteen
    | Twenty
    | TwentyOne
    | TwentyTwo
    | TwentyThree
    | TwentyFour
    | TwentyFive
    | TwentySix
    | TwentySeven
    | TwentyEight
    | TwentyNine
    | Thirty
    | ThirtyOne
    | ThirtyTwo;
  key: string;
};

/** @internal */
export const ThirtyTwo$inboundSchema: z.ZodType<
  ThirtyTwo,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("grammar_diversity"),
});

export function thirtyTwoFromJSON(
  jsonString: string,
): SafeParseResult<ThirtyTwo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThirtyTwo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThirtyTwo' from JSON`,
  );
}

/** @internal */
export const ThirtyOne$inboundSchema: z.ZodType<
  ThirtyOne,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("lexical_repetition"),
});

export function thirtyOneFromJSON(
  jsonString: string,
): SafeParseResult<ThirtyOne, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThirtyOne$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThirtyOne' from JSON`,
  );
}

/** @internal */
export const Thirty$inboundSchema: z.ZodType<Thirty, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("sentences_count"),
  });

export function thirtyFromJSON(
  jsonString: string,
): SafeParseResult<Thirty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Thirty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Thirty' from JSON`,
  );
}

/** @internal */
export const TwentyNine$inboundSchema: z.ZodType<
  TwentyNine,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("words_count"),
});

export function twentyNineFromJSON(
  jsonString: string,
): SafeParseResult<TwentyNine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyNine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyNine' from JSON`,
  );
}

/** @internal */
export const TwentyEight$inboundSchema: z.ZodType<
  TwentyEight,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("gse_english_level"),
});

export function twentyEightFromJSON(
  jsonString: string,
): SafeParseResult<TwentyEight, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyEight$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyEight' from JSON`,
  );
}

/** @internal */
export const TwentySeven$inboundSchema: z.ZodType<
  TwentySeven,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("flesch_reading_ease"),
});

export function twentySevenFromJSON(
  jsonString: string,
): SafeParseResult<TwentySeven, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentySeven$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentySeven' from JSON`,
  );
}

/** @internal */
export const TwentySix$inboundSchema: z.ZodType<
  TwentySix,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("most_repeated_words"),
});

export function twentySixFromJSON(
  jsonString: string,
): SafeParseResult<TwentySix, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentySix$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentySix' from JSON`,
  );
}

/** @internal */
export const TwentyFive$inboundSchema: z.ZodType<
  TwentyFive,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("keywords_match"),
  keywords: z.array(z.string()),
});

export function twentyFiveFromJSON(
  jsonString: string,
): SafeParseResult<TwentyFive, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyFive$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyFive' from JSON`,
  );
}

/** @internal */
export const TwentyFour$inboundSchema: z.ZodType<
  TwentyFour,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("levenshtein_distance"),
});

export function twentyFourFromJSON(
  jsonString: string,
): SafeParseResult<TwentyFour, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyFour$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyFour' from JSON`,
  );
}

/** @internal */
export const TwentyThree$inboundSchema: z.ZodType<
  TwentyThree,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("cosine_similarity"),
});

export function twentyThreeFromJSON(
  jsonString: string,
): SafeParseResult<TwentyThree, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyThree$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyThree' from JSON`,
  );
}

/** @internal */
export const TwentyTwo$inboundSchema: z.ZodType<
  TwentyTwo,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("meteor_score"),
});

export function twentyTwoFromJSON(
  jsonString: string,
): SafeParseResult<TwentyTwo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyTwo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyTwo' from JSON`,
  );
}

/** @internal */
export const TwentyOne$inboundSchema: z.ZodType<
  TwentyOne,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("rouge_n"),
});

export function twentyOneFromJSON(
  jsonString: string,
): SafeParseResult<TwentyOne, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TwentyOne$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TwentyOne' from JSON`,
  );
}

/** @internal */
export const Twenty$inboundSchema: z.ZodType<Twenty, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("bleu_score"),
  });

export function twentyFromJSON(
  jsonString: string,
): SafeParseResult<Twenty, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Twenty$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Twenty' from JSON`,
  );
}

/** @internal */
export const Nineteen$inboundSchema: z.ZodType<
  Nineteen,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("bert_score"),
});

export function nineteenFromJSON(
  jsonString: string,
): SafeParseResult<Nineteen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Nineteen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Nineteen' from JSON`,
  );
}

/** @internal */
export const Eighteen$inboundSchema: z.ZodType<
  Eighteen,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("moderations_google"),
});

export function eighteenFromJSON(
  jsonString: string,
): SafeParseResult<Eighteen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Eighteen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Eighteen' from JSON`,
  );
}

/** @internal */
export const Seventeen$inboundSchema: z.ZodType<
  Seventeen,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("moderations_openai"),
});

export function seventeenFromJSON(
  jsonString: string,
): SafeParseResult<Seventeen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Seventeen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Seventeen' from JSON`,
  );
}

/** @internal */
export const Sixteen$inboundSchema: z.ZodType<Sixteen, z.ZodTypeDef, unknown> =
  z.object({
    type: z.literal("is_valid_json"),
  });

export function sixteenFromJSON(
  jsonString: string,
): SafeParseResult<Sixteen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sixteen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sixteen' from JSON`,
  );
}

/** @internal */
export const Fifteen$inboundSchema: z.ZodType<Fifteen, z.ZodTypeDef, unknown> =
  z.object({
    type: z.literal("regex"),
    pattern: z.string(),
  });

export function fifteenFromJSON(
  jsonString: string,
): SafeParseResult<Fifteen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fifteen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fifteen' from JSON`,
  );
}

/** @internal */
export const Fourteen$inboundSchema: z.ZodType<
  Fourteen,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("one_line"),
});

export function fourteenFromJSON(
  jsonString: string,
): SafeParseResult<Fourteen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fourteen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fourteen' from JSON`,
  );
}

/** @internal */
export const Thirteen$inboundSchema: z.ZodType<
  Thirteen,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("length_greater_than"),
  value: z.number(),
});

export function thirteenFromJSON(
  jsonString: string,
): SafeParseResult<Thirteen, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Thirteen$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Thirteen' from JSON`,
  );
}

/** @internal */
export const Twelve$inboundSchema: z.ZodType<Twelve, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("length_between"),
    min: z.number(),
    max: z.number(),
  });

export function twelveFromJSON(
  jsonString: string,
): SafeParseResult<Twelve, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Twelve$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Twelve' from JSON`,
  );
}

/** @internal */
export const Eleven$inboundSchema: z.ZodType<Eleven, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("length_less_than"),
    value: z.number(),
  });

export function elevenFromJSON(
  jsonString: string,
): SafeParseResult<Eleven, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Eleven$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Eleven' from JSON`,
  );
}

/** @internal */
export const Ten$inboundSchema: z.ZodType<Ten, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("exact_match"),
  });

export function tenFromJSON(
  jsonString: string,
): SafeParseResult<Ten, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ten$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ten' from JSON`,
  );
}

/** @internal */
export const Nine$inboundSchema: z.ZodType<Nine, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("ends_with"),
    value: z.string(),
  });

export function nineFromJSON(
  jsonString: string,
): SafeParseResult<Nine, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Nine$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Nine' from JSON`,
  );
}

/** @internal */
export const Eight$inboundSchema: z.ZodType<Eight, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("start_with"),
    value: z.string(),
  });

export function eightFromJSON(
  jsonString: string,
): SafeParseResult<Eight, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Eight$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Eight' from JSON`,
  );
}

/** @internal */
export const Seven$inboundSchema: z.ZodType<Seven, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains_valid_link"),
  });

export function sevenFromJSON(
  jsonString: string,
): SafeParseResult<Seven, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Seven$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Seven' from JSON`,
  );
}

/** @internal */
export const Six$inboundSchema: z.ZodType<Six, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains_url"),
  });

export function sixFromJSON(
  jsonString: string,
): SafeParseResult<Six, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Six$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Six' from JSON`,
  );
}

/** @internal */
export const Five$inboundSchema: z.ZodType<Five, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains_email"),
  });

export function fiveFromJSON(
  jsonString: string,
): SafeParseResult<Five, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Five$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Five' from JSON`,
  );
}

/** @internal */
export const Four$inboundSchema: z.ZodType<Four, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains_any"),
    keywords: z.array(z.string()),
  });

export function fourFromJSON(
  jsonString: string,
): SafeParseResult<Four, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Four$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Four' from JSON`,
  );
}

/** @internal */
export const Three$inboundSchema: z.ZodType<Three, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains_all"),
    keywords: z.array(z.string()),
  });

export function threeFromJSON(
  jsonString: string,
): SafeParseResult<Three, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Three$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Three' from JSON`,
  );
}

/** @internal */
export const Two$inboundSchema: z.ZodType<Two, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains_none"),
    keywords: z.array(z.string()),
  });

export function twoFromJSON(
  jsonString: string,
): SafeParseResult<Two, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Two$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Two' from JSON`,
  );
}

/** @internal */
export const One$inboundSchema: z.ZodType<One, z.ZodTypeDef, unknown> = z
  .object({
    type: z.literal("contains"),
    value: z.string(),
  });

export function oneFromJSON(
  jsonString: string,
): SafeParseResult<One, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => One$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'One' from JSON`,
  );
}

/** @internal */
export const FunctionParams$inboundSchema: z.ZodType<
  FunctionParams,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => One$inboundSchema),
  z.lazy(() => Two$inboundSchema),
  z.lazy(() => Three$inboundSchema),
  z.lazy(() => Four$inboundSchema),
  z.lazy(() => Five$inboundSchema),
  z.lazy(() => Six$inboundSchema),
  z.lazy(() => Seven$inboundSchema),
  z.lazy(() => Eight$inboundSchema),
  z.lazy(() => Nine$inboundSchema),
  z.lazy(() => Ten$inboundSchema),
  z.lazy(() => Eleven$inboundSchema),
  z.lazy(() => Twelve$inboundSchema),
  z.lazy(() => Thirteen$inboundSchema),
  z.lazy(() => Fourteen$inboundSchema),
  z.lazy(() => Fifteen$inboundSchema),
  z.lazy(() => Sixteen$inboundSchema),
  z.lazy(() => Seventeen$inboundSchema),
  z.lazy(() => Eighteen$inboundSchema),
  z.lazy(() => Nineteen$inboundSchema),
  z.lazy(() => Twenty$inboundSchema),
  z.lazy(() => TwentyOne$inboundSchema),
  z.lazy(() => TwentyTwo$inboundSchema),
  z.lazy(() => TwentyThree$inboundSchema),
  z.lazy(() => TwentyFour$inboundSchema),
  z.lazy(() => TwentyFive$inboundSchema),
  z.lazy(() => TwentySix$inboundSchema),
  z.lazy(() => TwentySeven$inboundSchema),
  z.lazy(() => TwentyEight$inboundSchema),
  z.lazy(() => TwentyNine$inboundSchema),
  z.lazy(() => Thirty$inboundSchema),
  z.lazy(() => ThirtyOne$inboundSchema),
  z.lazy(() => ThirtyTwo$inboundSchema),
]);

export function functionParamsFromJSON(
  jsonString: string,
): SafeParseResult<FunctionParams, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FunctionParams$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FunctionParams' from JSON`,
  );
}

/** @internal */
export const EvaluatorResponseFunction$inboundSchema: z.ZodType<
  EvaluatorResponseFunction,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string(),
  description: z.string(),
  created: z.string().default("2026-07-23T11:48:29.370Z"),
  updated: z.string().default("2026-07-23T11:48:29.370Z"),
  updated_by_id: z.nullable(z.string()).optional(),
  guardrail_config: z.any().optional(),
  type: z.literal("function_eval"),
  function_params: z.union([
    z.lazy(() => One$inboundSchema),
    z.lazy(() => Two$inboundSchema),
    z.lazy(() => Three$inboundSchema),
    z.lazy(() => Four$inboundSchema),
    z.lazy(() => Five$inboundSchema),
    z.lazy(() => Six$inboundSchema),
    z.lazy(() => Seven$inboundSchema),
    z.lazy(() => Eight$inboundSchema),
    z.lazy(() => Nine$inboundSchema),
    z.lazy(() => Ten$inboundSchema),
    z.lazy(() => Eleven$inboundSchema),
    z.lazy(() => Twelve$inboundSchema),
    z.lazy(() => Thirteen$inboundSchema),
    z.lazy(() => Fourteen$inboundSchema),
    z.lazy(() => Fifteen$inboundSchema),
    z.lazy(() => Sixteen$inboundSchema),
    z.lazy(() => Seventeen$inboundSchema),
    z.lazy(() => Eighteen$inboundSchema),
    z.lazy(() => Nineteen$inboundSchema),
    z.lazy(() => Twenty$inboundSchema),
    z.lazy(() => TwentyOne$inboundSchema),
    z.lazy(() => TwentyTwo$inboundSchema),
    z.lazy(() => TwentyThree$inboundSchema),
    z.lazy(() => TwentyFour$inboundSchema),
    z.lazy(() => TwentyFive$inboundSchema),
    z.lazy(() => TwentySix$inboundSchema),
    z.lazy(() => TwentySeven$inboundSchema),
    z.lazy(() => TwentyEight$inboundSchema),
    z.lazy(() => TwentyNine$inboundSchema),
    z.lazy(() => Thirty$inboundSchema),
    z.lazy(() => ThirtyOne$inboundSchema),
    z.lazy(() => ThirtyTwo$inboundSchema),
  ]),
  key: z.string(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "updated_by_id": "updatedById",
    "guardrail_config": "guardrailConfig",
    "function_params": "functionParams",
  });
});

export function evaluatorResponseFunctionFromJSON(
  jsonString: string,
): SafeParseResult<EvaluatorResponseFunction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EvaluatorResponseFunction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EvaluatorResponseFunction' from JSON`,
  );
}
