/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  BudgetRestResponse,
  BudgetRestResponse$inboundSchema,
} from "./budgetrestresponse.js";

export type GetBudgetResponse = {
  /**
   * Requested budget.
   */
  budget: BudgetRestResponse;
};

/** @internal */
export const GetBudgetResponse$inboundSchema: z.ZodType<
  GetBudgetResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  budget: BudgetRestResponse$inboundSchema,
});

export function getBudgetResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBudgetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBudgetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBudgetResponse' from JSON`,
  );
}
