/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  McpSessionStatus,
  McpSessionStatus$inboundSchema,
} from "./mcpsessionstatus.js";

export type McpSession = {
  id?: string | undefined;
  mcpGatewayId?: string | undefined;
  mcpServerId?: string | undefined;
  accountId?: string | undefined;
  status?: McpSessionStatus | undefined;
  created?: string | undefined;
  updated?: string | undefined;
};

/** @internal */
export const McpSession$inboundSchema: z.ZodType<
  McpSession,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  mcp_gateway_id: z.string().optional(),
  mcp_server_id: z.string().optional(),
  account_id: z.string().optional(),
  status: McpSessionStatus$inboundSchema.optional(),
  created: z.string().optional(),
  updated: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "mcp_gateway_id": "mcpGatewayId",
    "mcp_server_id": "mcpServerId",
    "account_id": "accountId",
  });
});

export function mcpSessionFromJSON(
  jsonString: string,
): SafeParseResult<McpSession, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => McpSession$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'McpSession' from JSON`,
  );
}
