/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type MemoryStoreEmbeddingConfig = {
  /**
   * The embeddings model to use for the knowledge base in the format "provider/model" for public models or "workspaceKey@provider/model" for private workspace models. This model will be used to embed the chunks when they are added to the knowledge base. Refer to the (Supported models)[/docs/proxy/supported-models] to browse available models.
   */
  model: string;
};

/** @internal */
export const MemoryStoreEmbeddingConfig$inboundSchema: z.ZodType<
  MemoryStoreEmbeddingConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  model: z.string(),
});
/** @internal */
export type MemoryStoreEmbeddingConfig$Outbound = {
  model: string;
};

/** @internal */
export const MemoryStoreEmbeddingConfig$outboundSchema: z.ZodType<
  MemoryStoreEmbeddingConfig$Outbound,
  z.ZodTypeDef,
  MemoryStoreEmbeddingConfig
> = z.object({
  model: z.string(),
});

export function memoryStoreEmbeddingConfigToJSON(
  memoryStoreEmbeddingConfig: MemoryStoreEmbeddingConfig,
): string {
  return JSON.stringify(
    MemoryStoreEmbeddingConfig$outboundSchema.parse(memoryStoreEmbeddingConfig),
  );
}
export function memoryStoreEmbeddingConfigFromJSON(
  jsonString: string,
): SafeParseResult<MemoryStoreEmbeddingConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MemoryStoreEmbeddingConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MemoryStoreEmbeddingConfig' from JSON`,
  );
}
