/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ModelRef,
  ModelRef$inboundSchema,
  ModelRef$Outbound,
  ModelRef$outboundSchema,
} from "./modelref.js";

export const Mode = {
  Fallback: "fallback",
  Weighted: "weighted",
  RoundRobin: "round_robin",
} as const;
export type Mode = ClosedEnum<typeof Mode>;

export type ModelsConfig = {
  mode: Mode;
  models: Array<ModelRef> | null;
};

/** @internal */
export const Mode$inboundSchema: z.ZodNativeEnum<typeof Mode> = z.nativeEnum(
  Mode,
);
/** @internal */
export const Mode$outboundSchema: z.ZodNativeEnum<typeof Mode> =
  Mode$inboundSchema;

/** @internal */
export const ModelsConfig$inboundSchema: z.ZodType<
  ModelsConfig,
  z.ZodTypeDef,
  unknown
> = z.object({
  mode: Mode$inboundSchema,
  models: z.nullable(z.array(ModelRef$inboundSchema)),
});
/** @internal */
export type ModelsConfig$Outbound = {
  mode: string;
  models: Array<ModelRef$Outbound> | null;
};

/** @internal */
export const ModelsConfig$outboundSchema: z.ZodType<
  ModelsConfig$Outbound,
  z.ZodTypeDef,
  ModelsConfig
> = z.object({
  mode: Mode$outboundSchema,
  models: z.nullable(z.array(ModelRef$outboundSchema)),
});

export function modelsConfigToJSON(modelsConfig: ModelsConfig): string {
  return JSON.stringify(ModelsConfig$outboundSchema.parse(modelsConfig));
}
export function modelsConfigFromJSON(
  jsonString: string,
): SafeParseResult<ModelsConfig, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ModelsConfig$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ModelsConfig' from JSON`,
  );
}
