/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Expression, Expression$inboundSchema } from "./expression.js";
import { ModelsConfig, ModelsConfig$inboundSchema } from "./modelsconfig.js";

export type RoutingRule = {
  id: string;
  createdAt: Date;
  createdById: string;
  description?: string | undefined;
  displayName: string;
  enabled: boolean;
  expression?: Expression | undefined;
  modelsConfig?: ModelsConfig | undefined;
  priority: number;
  projectId: string;
  updatedAt: Date;
  updatedById: string;
};

/** @internal */
export const RoutingRule$inboundSchema: z.ZodType<
  RoutingRule,
  z.ZodTypeDef,
  unknown
> = z.object({
  _id: z.string(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  created_by_id: z.string(),
  description: z.string().optional(),
  display_name: z.string(),
  enabled: z.boolean(),
  expression: Expression$inboundSchema.optional(),
  models_config: ModelsConfig$inboundSchema.optional(),
  priority: z.number().int(),
  project_id: z.string(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  updated_by_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "_id": "id",
    "created_at": "createdAt",
    "created_by_id": "createdById",
    "display_name": "displayName",
    "models_config": "modelsConfig",
    "project_id": "projectId",
    "updated_at": "updatedAt",
    "updated_by_id": "updatedById",
  });
});

export function routingRuleFromJSON(
  jsonString: string,
): SafeParseResult<RoutingRule, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RoutingRule$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RoutingRule' from JSON`,
  );
}
