/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ToolFailedEventData = {
  /**
   * Unique identifier for the tool in the tool registry
   */
  toolId: string;
  /**
   * Unique identifier matching the tool call that failed
   */
  toolCallId: string;
  /**
   * Error message describing why the tool failed
   */
  error: string;
};

/**
 * Emitted when a tool execution fails. Contains error details.
 */
export type ToolFailedEvent = {
  type: "tool.failed";
  /**
   * ISO timestamp of when the event occurred
   */
  timestamp: string;
  data: ToolFailedEventData;
};

/** @internal */
export const ToolFailedEventData$inboundSchema: z.ZodType<
  ToolFailedEventData,
  z.ZodTypeDef,
  unknown
> = z.object({
  toolId: z.string(),
  toolCallId: z.string(),
  error: z.string(),
});

export function toolFailedEventDataFromJSON(
  jsonString: string,
): SafeParseResult<ToolFailedEventData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolFailedEventData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolFailedEventData' from JSON`,
  );
}

/** @internal */
export const ToolFailedEvent$inboundSchema: z.ZodType<
  ToolFailedEvent,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("tool.failed"),
  timestamp: z.string(),
  data: z.lazy(() => ToolFailedEventData$inboundSchema),
});

export function toolFailedEventFromJSON(
  jsonString: string,
): SafeParseResult<ToolFailedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolFailedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolFailedEvent' from JSON`,
  );
}
