/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { agentsListTasks } from "../../funcs/agentsListTasks.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAgentTasksRequest$inboundSchema,
};

export const tool$agentsListTasks: ToolDefinition<typeof args> = {
  name: "agents-list-tasks",
  description: `List all tasks for an agent

Retrieves a paginated list of all tasks associated with a specific agent, optionally filtered by status.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await agentsListTasks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
