/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { evalsEndsWith } from "../../funcs/evalsEndsWith.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.EvalsEndsWithRequestBody$inboundSchema.optional(),
};

export const tool$evalsEndsWith: ToolDefinition<typeof args> = {
  name: "evals-ends-with",
  description: `Run Ends With Evaluator`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await evalsEndsWith(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
